### ISSUE TITLE
Zoomed-in backgrounds on mobile phone

### ISSUE THREAD

**Issue by dijonkitchen** [cortlandtlabs/cortlandtlabs.github.io#13]
This seems to happen only on actual phones, not on Chrome Dev Tools. 

Tested on Chrome and Safari on an iPhone 6S as well as on Simulator.

**Comment by jhack32** [comment]
Zoomed in? Doesn't look zoomed in on my phone

**Comment by dijonkitchen** [comment]
Maybe it's an iPhone thing then. Let's see what @aattsai says.
