### ISSUE TITLE
Add Didot font to asset so it works across platform

### ISSUE THREAD

**Issue by aattsai** [cortlandtlabs/cortlandtlabs.github.io#39]
### Expected behavior
Landing page should display Didot font

### Actual behavior
On Android devices, a generic font is displayed

### Steps to reproduce the behavior
Use an Android device to view the landing page.

**Comment by dijonkitchen** [comment]
I think you meant that last line for a possible solution, not how to reproduce.

**Comment by dijonkitchen** [comment]
Related to #30

**Comment by aattsai** [comment]
Didot is no longer used
